#!/usr/bin/env bash
#figure your domain zone so that the subdomain www points to your load-balancer IP (lb-01). 
if [ "$#" -eq 2 ]
then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "lb-01"
    print_info "web-01.$1" "web-01"
    print_info "web-02.$1" "web-02"

#task 0 weeb world wide
