#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80

sudo apt-get -y update

#When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get -y install nginx
#write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself

echo 'Hello World!' > /var/www/html/index.nginx-debian.html


sudo service nginx start

#task 1 
