#!/usr/bin/env bash

# thia is the fifth task on the project


#it is about IP adress 5  is the host 

#if the network. how it works


if [ "$" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$" -c 5


    fi
