#!/usr/bin/env bash
#debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80.
#task 0 web stack debugging

cd /etc/nginx/sites-enabled/ || exit; 
#ubuntu container 
rm default; 

#task web stack debugging 1
#cok  guzel can ask 
ln -s /etc/nginx/sites-available/default default;
