#!/usr/bin/env bash
#task 1 web debugging


#Your Bash script must be 5 lines long or less. There must be a new line at the end of the file
#You must respect usual Bash script requirements, you cannot use ;
#You cannot use &&
#You cannot use wget

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default

#service (init) must say that nginx is not running ← for real
kill -9 "$(cat /var/run/nginx.pid)"
