#!/usr/bin/env bash

# task 1 of the 0x08 bash script

#this is the new task

cp /etc/hosts ~/hosts.new #copy etc hosts to hosts new

echo '2i8.8.8.8 facebook.com' ~/hosts.new #reflect 8.8.8.8 to hosts new facebook

echo 's/127.0.0.1/127.0.0.2/' ~/hosts.new #127.0.0 to hosts new

cp -f ~/hosts.new /etc/hosts
